[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day-1"
[[bin]]
name = "day-4"

[lib]
name = "advent"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.2"
